apiVersion: v1
kind: PersistantVolume
metadata:
  name: pv1
spec:
     capacity:
          storage: 20 Gi
     accessModes: 
        - ReadWriteOnce
     PersistantVolumeReclaimPolicy: Recycle
     awsElasticBlockStore:
         volumeID: vol-946453838649
         fsType: ext4
